Remove "After" in automount example
rclone/rclone pull request #5911
Opened 2022-01-12 15:34 UTC by maxxer

According to [systemd.automount](https://www.freedesktop.org/software/systemd/man/systemd.automount.html) manual

> Note that automount units are separate from the mount itself, so you should 
> not set After= or Requires= for mount dependencies here. 
> For example, you should not set After=network-online.target or 
> similar on network filesystems. Doing so may result in an ordering cycle.

#### What is the purpose of this change?

Small change in mount documentation 

#### Checklist

- [ ] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [ ] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

2022-09-22 09:11 UTC, albertony commented
Closes #6459

2022-09-22 11:18 UTC, ncw approved these changes
Thank you for finding and fixing this - much appreciated :-)

2022-09-22 11:20 UTC, ncw commented
@albertony can you merge this once we've had the OK back from @wilcooo 's tests - thanks!

2022-09-23 18:56 UTC, wilcooo requested changes
I suspect the `After` shoulld be removed from the `mnt-data.mount` file as well, as I kept getting dependency cycles even after removing the line from `mnt-data.automount`. See my issue #6459 for more details.

2022-09-26 17:11 UTC, merged

2022-10-02 12:23 UTC, yuraih commented
This pull request is a duplicate of https://github.com/rclone/rclone/pull/5818 that was reported a year ago.