s3: Add Liara LOS to provider list
rclone/rclone pull request #6516
Opened 2022-10-25 14:04 UTC by vashian

#### What is the purpose of this change?

#### Was the change discussed in an issue or in the forum before?

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

2022-10-25 14:05 UTC, vashian commented
@ncw Liara Object Storage (**LOS**) is a cloud object storage service and is  compatible with S3.

2022-10-26 11:23 UTC, 7qqr approved these changes

2022-11-07 08:38 UTC, albertony requested changes

2022-11-07 08:38 UTC, albertony commented on docs/content/_index.md
> +{{< provider name="Liara Object Storage (LOS)" home="https://liara.ir/landing/%D9%87%D8%A7%D8%B3%D8%AA-%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-download-host" config="/s3/#liara-object-storage-los" >}}
The home url here should be a regular human-readable web page, and I think the current is an API endpoint?

2022-11-07 08:38 UTC, albertony commented on docs/content/s3.md
> +{{< provider name="Liara Object Storage (LOS)" home="https://liara.ir/landing/%D9%87%D8%A7%D8%B3%D8%AA-%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-download-host" config="/s3/#liara-object-storage-los" >}}
The home url here should be a regular human-readable web page, and I think the current is an API endpoint?

2022-11-07 08:38 UTC, albertony commented on docs/content/s3.md
>  {{< rem autogenerated options start" - DO NOT EDIT - instead edit fs.RegInfo in backend/s3/s3.go then run make backenddocs" >}}
Did you notice this? Its easy to miss, so I just wanted to make sure you did not manually edit text below here - which are not also reflected in the s3.go source and would therefore be lost.

2022-11-07 12:09 UTC, ncw commented on docs/content/_index.md
> +{{< provider name="Liara Object Storage (LOS)" home="https://liara.ir/landing/%D9%87%D8%A7%D8%B3%D8%AA-%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-download-host" config="/s3/#liara-object-storage-los" >}}
Note that this bit `%D9%87%D8%A7%D8%B3%D8%AA-%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF` is UTF-encoded text which displays as `هاست-دانلود`.

"download host" seems to be the name of the service in English and with google translate the page does talk about s3 interfaces, its just quite a long way down the page.

However this page looks like it is the target for a Advertising campaign and not the main info page so I'm not sure this is the right page to link to?

I found this page which is the docs page https://docs.liara.ir/buckets/about but we usually link to the providers main page about the service.

2022-11-07 18:13 UTC, mhemrg commented on docs/content/_index.md
> +{{< provider name="Liara Object Storage (LOS)" home="https://liara.ir/landing/%D9%87%D8%A7%D8%B3%D8%AA-%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-download-host" config="/s3/#liara-object-storage-los" >}}
This is the landing page of the product written in Farsi.
Liara is a cloud provider and Object Storage is one of their services.

2022-11-08 16:29 UTC, ncw reviewed
Please can you drop the changes to the autogenerated part of s3.md

I will merge after that - thank you :-)

2022-11-11 08:03 UTC, vashian commented
Using the new URL `liara.ir/landing/object-storage`
Now it's human-readable without any encoded character.

Also, drop the changes from **autogenerated options** part.

2022-11-25 08:51 UTC, vashian commented
@ncw Unfortunately I haven't heard from you in a while. Could you please tell me what went wrong?

2022-11-25 11:40 UTC, ncw commented
@vashian sorry, I'm waiting for an update from you to remove the auto generated content from s3.md - otherwise your PR looks fine.  So remove all the changes in s3.md between

```
{{< rem autogenerated options start" - DO NOT EDIT - instead edit fs.RegInfo in backend/s3/s3.go then run make backenddocs" >}}
```

and

```
{{< rem autogenerated options stop >}}
```

These will be put in as part of the release process - I prefer not to add them at this point.

Thank you

2022-11-26 10:14 UTC, vashian commented
> @vashian sorry, I'm waiting for an update from you to remove the auto generated content from s3.md - otherwise your PR looks fine. So remove all the changes in s3.md between
> 
> ```
> {{< rem autogenerated options start" - DO NOT EDIT - instead edit fs.RegInfo in backend/s3/s3.go then run make backenddocs" >}}
> ```
> 
> and
> 
> ```
> {{< rem autogenerated options stop >}}
> ```
> 
> These will be put in as part of the release process - I prefer not to add them at this point.
> 
> Thank you

@ncw I appreciate it. Thank you for your time.

2022-11-30 14:55 UTC, albertony approved these changes

2022-12-06 12:25 UTC, ncw approved these changes
That looks great - I'll merge now - thank you :-)

2022-12-06 12:25 UTC, merged