Add IBM IAM signer
rclone/rclone pull request #8157
Opened 2024-10-31 02:07 UTC by minbaev

#### What is the purpose of this change?

Custom IBM IAM signer to sign HTTP requests with IBM IAM token
#### Was the change discussed in an issue or in the forum before?

[LINK to issue](https://github.com/rclone/rclone/issues/7617)
#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [X] I have added tests for all changes in this PR if appropriate.
- [X] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

2025-01-11 20:14 UTC, ncw requested changes
Sorry I missed this PR :-(

It looks very useful.

It needs some docs in the ibmcos provider section of `docs/content/s3.md`.

I put some things which need fixing inline.

Thank you for doing this :-)

2025-01-11 20:14 UTC, ncw commented on backend/ibmcos/ibmSigner.go
> +	fmt.Println("SignHTTP called") // Debug print
Remove please.

2025-01-11 20:14 UTC, ncw commented on backend/ibmcos/ibmSigner.go
> +package ibmcos
Can you put this into `backend/s3` as `ibm_signer.go` please. I don't think it needs to be its own package.

2025-01-11 20:14 UTC, ncw commented on backend/s3/s3.go
> +	APIKey                string               `config:"api_key"`
There don't appear to be matching config definitions for `APIKey` or `InstanceID`. Which also means they have no help.

Since these are ibm specific they should probably be prefixed `ibmcos_api_key` and `ibmcos_resource_instance_id`.

2025-01-11 20:14 UTC, ncw commented on backend/s3/s3.go
> +			options = append(options, func(s3Opt *s3.Options) {
Probably only do this if `opt.IBMCOSAPIKey` and `opt.IBMCOSInstanceID`  are set?

2025-01-11 20:14 UTC, ncw commented
Can you rebase it on master too please and force push - thanks.

2025-01-15 04:34 UTC, minbaev commented on backend/ibmcos/ibmSigner.go
> +	fmt.Println("SignHTTP called") // Debug print
addressed

2025-01-15 04:34 UTC, minbaev commented on backend/s3/s3.go
> +	APIKey                string               `config:"api_key"`
addressed

2025-01-15 04:34 UTC, minbaev commented on backend/s3/s3.go
> +			options = append(options, func(s3Opt *s3.Options) {
addressed

2025-01-15 04:34 UTC, minbaev commented on backend/ibmcos/ibmSigner.go
> +package ibmcos
done

2025-01-15 04:36 UTC, minbaev commented
Hi @ncw thanks for reviewing my pr. I addressed your comments, added docs, etc. Could you please take a look at it?

2025-01-21 14:37 UTC, minbaev commented
Hi @ncw reaching out again. could you please take a look at this pr? i have addressed the changes you requested

2025-01-21 17:50 UTC, ncw approved these changes
This looks very nice now - thank you :-)

I'll merge provided the CI passes.

Thanks

2025-01-21 17:59 UTC, ncw commented
Looks like this needs a bit of fixing up - there are some minor lint failures, but the test failures need looking at - thanks

2025-01-21 21:22 UTC, minbaev commented
@ncw thank you i will take a look at that

2025-01-22 10:53 UTC, ncw commented
Ping me here when you want me to take another look - thanks

2025-01-22 21:13 UTC, minbaev commented
@ncw i added fixes, please take another look. looks like i can't kickoff the ci workflow (since it's my first pr to this repo i think)

2025-01-24 15:20 UTC, minbaev commented
Hi @ncw can we merge the code?

2025-01-27 15:16 UTC, minbaev commented
Hi @ncw sorry to bother you, but is it fine to merge the change?
in case you are busy, is there someone who has merge privileges and with whom i can work? Thank you

2025-01-31 14:47 UTC, minbaev commented
Hi
Can somebody with write access please merge this pr?

@lostb1t, @Cnly, @buengese, @calisro, @darthShadow, @ivandeex, @henrybear327, @negative0, @childish-sambino
Sorry for tagging lots of you, not sure who to ask to look at this
thank you

2025-01-31 18:38 UTC, ncw commented
Sorry for the delay I've been out of the office for a few days.

I ran the CI do we can check that.

It is looking great, though I just noticed something I should have noticed before - can you rename the files `ibmSigner` to `ibm_signer` or `ibmsigner` whichever you prefer. All our `.go` source files are lower case at the moment!

If you can do that then we can merge - thank you.

2025-01-31 18:52 UTC, minbaev commented
> Sorry for the delay I've been out of the office for a few days.
> 
> I ran the CI do we can check that.
> 
> It is looking great, though I just noticed something I should have noticed before - can you rename the files `ibmSigner` to `ibm_signer` or `ibmsigner` whichever you prefer. All our `.go` source files are lower case at the moment!
> 
> If you can do that then we can merge - thank you.

Done

2025-02-03 11:29 UTC, merged

2025-02-03 11:29 UTC, ncw commented
Thank you @minbaev :-)