http: trim initial slash building url
rclone/rclone pull request #8262
Opened 2024-12-23 14:49 UTC by hiddenmarten

#### What is the purpose of this change?

Fixing issue: https://github.com/rclone/rclone/issues/8261

#### Was the change discussed in an issue or in the forum before?

No, it wasn't.

#### Checklist

- [X] I have read the [contribution guidelines](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-new-feature-or-bug-fix).
- [X] I have added tests for all changes in this PR if appropriate.
- [X] I have added documentation for the changes if appropriate.
- [X] All commit messages are in [house style](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [X] I'm done, this Pull Request is ready for review :-)

2024-12-30 14:25 UTC, hiddenmarten commented
Hi, @ncw!

Should I do something in order to get a review?  :)

2024-12-31 12:58 UTC, ncw requested changes
This fix looks great - thank you.

Can you add a test for it? Either add a test like this one or put something in this test trying NewObject on a remote with `/` at the start.

https://github.com/rclone/rclone/blob/a389a2979b0a4726e180478f51074bc4a64a9826/backend/http/http_internal_test.go#L167-L171

2024-12-31 12:59 UTC, ncw commented
(Sorry for the delay reviewing @hiddenmarten - very busy!)

2025-01-08 15:12 UTC, hiddenmarten commented
Hi @ncw,

As requested, I’ve added a test to check the behavior with leading slashes. 😊

2025-01-09 17:38 UTC, ncw approved these changes
Looks great - thank you @hiddenmarten 

Will merge now.

2025-01-09 17:40 UTC, merged